name: publish to GHCR
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: net-monitor
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Notation with azure-kv plugin
        uses: Duffney/setup-notation@v1.0.0
        with:
          version: 1.0.0-rc.7
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and Publish Docker image
        run: |
          github_actor_lowercase=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ${{ env.REGISTRY }}/${github_actor_lowercase}/${{ env.IMAGE_NAME }}:${{ github.sha }} https://github.com/wabbit-networks/net-monitor.git#main
          docker push ${{ env.REGISTRY }}/${github_actor_lowercase}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Sign image
        run: |
          github_actor_lowercase=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          notation sign --signature-format cose ${{ env.REGISTRY }}/${github_actor_lowercase}/${{ env.IMAGE_NAME }}:${{ github.sha }}