name: publish to Azure Container Registry
on: [push]

env:
  REGISTRY: ballerina.azurecr.io 
  IMAGE_NAME: ballerina
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: debug
        run: VAR=$(terraform output -raw akv_name) && echo $VAR
        working-directory: ./terraform

      - name: Export Terraform output
        id: tf 
        run: |
          echo "AKV_NAME=$(terraform output -raw akv_name)" >> $GITHUB_OUTPUT
          echo "ACR_NAME=$(terraform output -raw acr_name)" >> $GITHUB_OUTPUT
          echo "CERT_NAME=$(terraform output -raw cert_name)" >> $GITHUB_OUTPUT
        working-directory: ./terraform

      - name: Get Signing Cert Key ID & Notation Credentials
        id: kid
        run: |
          keyID=$(az keyvault certificate show \
            --vault-name ${{ steps.tf.outputs.AKV_NAME }} --name ${{ steps.tf.outputs.CERT_NAME }} \
            --query "kid" --only-show-errors --output tsv)

          tokenPassword=$(az acr token create \
            --name "${{ steps.tf.outputs.CERT_NAME }}" \
            --registry ${{ steps.tf.outputs.ACR_NAME }} \
            --scope-map _repositories_admin \
            --query 'credentials.passwords[0].value' \
            --only-show-errors \
            --output tsv)

          echo "SIGN_CERT_KEY_ID=${keyID}" >> $GITHUB_OUTPUT
          echo "NOTATION_USERNAME=${{ steps.tf.outputs.CERT_NAME }}" >> $GITHUB_OUTPUT
          echo "NOTATION_PASSWORD=${tokenPassword}" >> $GITHUB_OUTPUT
      - name: Setup Notation with azure-kv plugin
        uses: Duffney/setup-notation@v1.0.0
        with:
          version: 1.0.0-rc.7
          key_name: ${{ steps.tf.outputs.CERT_NAME }} 
          certificate_key_id: ${{ steps.kid.outputs.SIGN_CERT_KEY_ID }} 
          plugin_name: notation-azure-kv
          plugin_version: 0.6.0 
          #      - name: Build and Publish Docker image
          #        run: |
          #          docker build --no-cache=true . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          #          docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          #          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          #      - name: Verify key generation
          #        run: notation key list 
          #      - name: Sign the published Docker image
          #        run: notation sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
      - name: Terraform destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform
