name: publish
on: [push]
env:
  REGISTRY: ghcr.io
  USER: Duffney
  IMAGE_NAME: net-monitor
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Notation with azure-kv plugin
        uses: Duffney/setup-notation@v1.0.0
        with:
          version: 1.0.0-rc.7
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Duffney
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and Publish Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:v${{ github.run_number} https://github.com/wabbit-networks/net-monitor.git#main
          docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:v${{ github.run_number}
      - name: Sign image
        run: notation sign --signature-format cose ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:v${{ github.run_number}